// <auto-generated />
using GuideAPI.Persistens;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuideAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuideAPI.Models.ColorPalette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<string>("Description")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .HasMaxLength(10);

                    b.Property<int>("StyleSheetId");

                    b.HasKey("Id");

                    b.HasIndex("StyleSheetId");

                    b.ToTable("ColorPalette");
                });

            modelBuilder.Entity("GuideAPI.Models.StyleSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("StyleSheet");
                });

            modelBuilder.Entity("GuideAPI.Models.Typepography", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<int>("StyleSheetId");

                    b.Property<string>("Text");

                    b.Property<string>("Typeface");

                    b.HasKey("Id");

                    b.HasIndex("StyleSheetId");

                    b.ToTable("Typepography");
                });

            modelBuilder.Entity("GuideAPI.Models.ColorPalette", b =>
                {
                    b.HasOne("GuideAPI.Models.StyleSheet", "StyleSheet")
                        .WithMany("ColorPalette")
                        .HasForeignKey("StyleSheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GuideAPI.Models.Typepography", b =>
                {
                    b.HasOne("GuideAPI.Models.StyleSheet", "StyleSheet")
                        .WithMany("Typepographie")
                        .HasForeignKey("StyleSheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
